// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrFRDFgAnYNQU-59Tvdv02VjOG86xKzk',
    appId: '1:541296271413:web:15dd8dc111ae844d89d17c',
    messagingSenderId: '541296271413',
    projectId: 'ex-firbase-90c46',
    authDomain: 'ex-firbase-90c46.firebaseapp.com',
    storageBucket: 'ex-firbase-90c46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJKDXlb83ckshK6lQR6_9127fhYHm_0o',
    appId: '1:541296271413:android:e8ee8023ef75a42e89d17c',
    messagingSenderId: '541296271413',
    projectId: 'ex-firbase-90c46',
    storageBucket: 'ex-firbase-90c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC80tDfB-R8Yutdg8ysknsK43ROSjA8xk',
    appId: '1:541296271413:ios:d16c1d195c43181089d17c',
    messagingSenderId: '541296271413',
    projectId: 'ex-firbase-90c46',
    storageBucket: 'ex-firbase-90c46.appspot.com',
    iosClientId:
        '541296271413-fq57b1vqfpkv37cb7uujmb3jjnettg9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.exFirbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC80tDfB-R8Yutdg8ysknsK43ROSjA8xk',
    appId: '1:541296271413:ios:d16c1d195c43181089d17c',
    messagingSenderId: '541296271413',
    projectId: 'ex-firbase-90c46',
    storageBucket: 'ex-firbase-90c46.appspot.com',
    iosClientId:
        '541296271413-fq57b1vqfpkv37cb7uujmb3jjnettg9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.exFirbase',
  );
}
